name: Scrape Domains and Generate CSVs

on:
  schedule:
    - cron: '0 9 * * 1'  # Runs every Monday at 09:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Run scraper script
        run: python .github/workflows/scripts/scrape_domains.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-domain-lists
          git add Defender/IOCs/*.csv Defender/IOCs/error-log/*
          git commit -m "Update domain lists and error logs"
          git push origin update-domain-lists
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-domain-lists
          title: "Update domain lists"
          body: "Automated update of domain lists and error logs."
          commit-message: "Update domain lists and logs"
          delete-branch: true
          author: "MarshyP <130765345+Marshyp@users.noreply.github.com>"
